name: 'TF-rolling Infrastructure'

on:
  push:
    branches:
      - 'cleanup'

jobs:
  tf-plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: 


    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # "Configure AWS Credentials" Action For GitHub Actions
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-duration-seconds: 1200
          aws-region: us-east-1



  tf-apply-prod:
    if: github.ref == 'refs/heads/staging'
    needs: tf-plan
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-duration-seconds: 1200
          aws-region: us-east-1



      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init 

      - name: Terraform apply staging
        run: terraform destroy --auto-approve


